# A rede padrão do projeto, que já existe
networks:
  default:
    external: true
    name: t1a-pages_default

services:
  nginx:
    image: nginx:latest
    volumes:
      - "t1a-pages_wordpress-t1a_data:/var/www/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - wordpress
    networks: # NOVO: Conecta o Nginx à rede padrão
      - default

  wordpress:
    image: wordpress:fpm
    restart: always
    volumes:
      - "t1a-pages_wordpress-t1a_data:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: t1a-pages_wordpress-t1a-db
      WORDPRESS_DB_USER: mariadb
      WORDPRESS_DB_PASSWORD: S949c242aff43675cebf6
      WORDPRESS_DB_NAME: t1a-pages
    networks: # NOVO: Conecta o Wordpress à rede padrão
      - default

  redis:
    image: redis:alpine
    restart: always
    networks: # NOVO: Conecta o Redis à rede padrão
      - default

volumes:
  t1a-pages_wordpress-t1a_data:
    external: true
  t1a-pages_wordpress-t1a-db_data:
    external: true
